# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuessMe.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(280, 226)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/GuessMeIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 281, 212))
        self.stackedWidget.setStyleSheet(_fromUtf8("background-color: rgb(89, 171, 227);"))
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.frame_1 = QtGui.QFrame(self.page_1)
        self.frame_1.setGeometry(QtCore.QRect(0, 0, 281, 211))
        self.frame_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.pushButton_Help = QtGui.QPushButton(self.frame_1)
        self.pushButton_Help.setGeometry(QtCore.QRect(100, 80, 75, 23))
        self.pushButton_Help.setStyleSheet(_fromUtf8("background-color: rgb(197, 239, 247);"))
        self.pushButton_Help.setObjectName(_fromUtf8("pushButton_Help"))
        self.pushButton_Start = QtGui.QPushButton(self.frame_1)
        self.pushButton_Start.setGeometry(QtCore.QRect(100, 50, 75, 23))
        self.pushButton_Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Start.setWhatsThis(_fromUtf8(""))
        self.pushButton_Start.setStyleSheet(_fromUtf8("background-color: rgb(197, 239, 247);"))
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.pushButton_Exit = QtGui.QPushButton(self.frame_1)
        self.pushButton_Exit.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.pushButton_Exit.setStyleSheet(_fromUtf8("background-color: rgb(197, 239, 247);"))
        self.pushButton_Exit.setObjectName(_fromUtf8("pushButton_Exit"))
        self.progressBar = QtGui.QProgressBar(self.frame_1)
        self.progressBar.setGeometry(QtCore.QRect(0, 200, 280, 12))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.frame_2 = QtGui.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 281, 211))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_Attempt = QtGui.QLabel(self.frame_2)
        self.label_Attempt.setGeometry(QtCore.QRect(10, 10, 90, 20))
        self.label_Attempt.setObjectName(_fromUtf8("label_Attempt"))
        self.lineEdit_EnterValue = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_EnterValue.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.lineEdit_EnterValue.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.lineEdit_EnterValue.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_EnterValue.setObjectName(_fromUtf8("lineEdit_EnterValue"))
        self.label_Level = QtGui.QLabel(self.frame_2)
        self.label_Level.setGeometry(QtCore.QRect(220, 10, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Level.setFont(font)
        self.label_Level.setObjectName(_fromUtf8("label_Level"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 50, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Number_CorrectWrong = QtGui.QLabel(self.frame_2)
        self.Number_CorrectWrong.setGeometry(QtCore.QRect(50, 70, 181, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.Number_CorrectWrong.setFont(font)
        self.Number_CorrectWrong.setText(_fromUtf8(""))
        self.Number_CorrectWrong.setTextFormat(QtCore.Qt.AutoText)
        self.Number_CorrectWrong.setWordWrap(True)
        self.Number_CorrectWrong.setObjectName(_fromUtf8("Number_CorrectWrong"))
        self.progressBar_2 = QtGui.QProgressBar(self.frame_2)
        self.progressBar_2.setGeometry(QtCore.QRect(0, 200, 280, 12))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.label_Range = QtGui.QLabel(self.frame_2)
        self.label_Range.setGeometry(QtCore.QRect(110, 40, 70, 20))
        self.label_Range.setText(_fromUtf8(""))
        self.label_Range.setObjectName(_fromUtf8("label_Range"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.frame_3 = QtGui.QFrame(self.page_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 281, 211))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.Win_Lost = QtGui.QLabel(self.frame_3)
        self.Win_Lost.setGeometry(QtCore.QRect(60, 40, 161, 20))
        self.Win_Lost.setAutoFillBackground(False)
        self.Win_Lost.setText(_fromUtf8(""))
        self.Win_Lost.setObjectName(_fromUtf8("Win_Lost"))
        self.pushButton_Start_2 = QtGui.QPushButton(self.frame_3)
        self.pushButton_Start_2.setGeometry(QtCore.QRect(100, 100, 75, 23))
        self.pushButton_Start_2.setStyleSheet(_fromUtf8("background-color: rgb(197, 239, 247);"))
        self.pushButton_Start_2.setObjectName(_fromUtf8("pushButton_Start_2"))
        self.pushButton_MainMenu = QtGui.QPushButton(self.frame_3)
        self.pushButton_MainMenu.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.pushButton_MainMenu.setStyleSheet(_fromUtf8("background-color: rgb(197, 239, 247);"))
        self.pushButton_MainMenu.setObjectName(_fromUtf8("pushButton_MainMenu"))
        self.pushButton_Exit_2 = QtGui.QPushButton(self.frame_3)
        self.pushButton_Exit_2.setGeometry(QtCore.QRect(180, 100, 75, 23))
        self.pushButton_Exit_2.setStyleSheet(_fromUtf8("background-color: rgb(197, 239, 247);"))
        self.pushButton_Exit_2.setObjectName(_fromUtf8("pushButton_Exit_2"))
        self.progressBar_3 = QtGui.QProgressBar(self.frame_3)
        self.progressBar_3.setGeometry(QtCore.QRect(0, 200, 280, 12))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.Help = QtGui.QTextBrowser(self.page)
        self.Help.setGeometry(QtCore.QRect(10, 30, 256, 151))
        self.Help.setFrameShadow(QtGui.QFrame.Raised)
        self.Help.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Help.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Help.setObjectName(_fromUtf8("Help"))
        self.pushButton_Help_back = QtGui.QPushButton(self.page)
        self.pushButton_Help_back.setGeometry(QtCore.QRect(20, 182, 75, 23))
        self.pushButton_Help_back.setStyleSheet(_fromUtf8("background-color: rgb(197, 239, 247);"))
        self.pushButton_Help_back.setObjectName(_fromUtf8("pushButton_Help_back"))
        self.Help_title_GuessMe = QtGui.QLabel(self.page)
        self.Help_title_GuessMe.setGeometry(QtCore.QRect(100, 10, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Help_title_GuessMe.setFont(font)
        self.Help_title_GuessMe.setObjectName(_fromUtf8("Help_title_GuessMe"))
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 20))
        self.menubar.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.971591, y2:0.034, stop:0 rgba(68, 108, 179, 255), stop:0.960227 rgba(197, 239, 247, 255));\n"
"\n"
""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionStats = QtGui.QAction(MainWindow)
        self.actionStats.setObjectName(_fromUtf8("actionStats"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionMain_Menu = QtGui.QAction(MainWindow)
        self.actionMain_Menu.setObjectName(_fromUtf8("actionMain_Menu"))
        self.menuFile.addAction(self.actionMain_Menu)
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStats)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_Start, self.pushButton_Help)
        MainWindow.setTabOrder(self.pushButton_Help, self.pushButton_Exit)
        MainWindow.setTabOrder(self.pushButton_Exit, self.lineEdit_EnterValue)
        MainWindow.setTabOrder(self.lineEdit_EnterValue, self.pushButton_Start_2)
        MainWindow.setTabOrder(self.pushButton_Start_2, self.pushButton_MainMenu)
        MainWindow.setTabOrder(self.pushButton_MainMenu, self.pushButton_Exit_2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Guess Me", None))
        self.pushButton_Help.setText(_translate("MainWindow", "Help", None))
        self.pushButton_Start.setText(_translate("MainWindow", "Start", None))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit", None))
        self.label_Attempt.setText(_translate("MainWindow", "Attempts Left: ", None))
        self.label_Level.setText(_translate("MainWindow", "Level", None))
        self.label_2.setText(_translate("MainWindow", "Enter No", None))
        self.pushButton_Start_2.setText(_translate("MainWindow", "Start", None))
        self.pushButton_MainMenu.setText(_translate("MainWindow", "Main Menu", None))
        self.pushButton_Exit_2.setText(_translate("MainWindow", "Exit", None))
        self.pushButton_Help_back.setText(_translate("MainWindow", "Back", None))
        self.Help_title_GuessMe.setText(_translate("MainWindow", "     GuessMe", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.actionStats.setText(_translate("MainWindow", "Stats", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionMain_Menu.setText(_translate("MainWindow", "Main Menu", None))

import GuessMeResource_rc
